



<!DOCTYPE html>
<html>
<head>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
 <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" >
 
 <meta name="ROBOTS" content="NOARCHIVE">
 
 <link rel="icon" type="image/vnd.microsoft.icon" href="https://ssl.gstatic.com/codesite/ph/images/phosting.ico">
 
 
 <script type="text/javascript">
 
 (function(){(function(){function c(a){this.t={};this.tick=function(a,b,c){b=void 0!=c?c:(new Date).getTime();this.t[a]=b;if(void 0==c)try{window.console.timeStamp("CSI/"+a)}catch(d){}};this.tick("start",null,a)}var a;window.performance&&(a=window.performance.timing);var b=a?new c(a.responseStart):new c;window.jstiming={Timer:c,load:b};a&&(b=a.navigationStart,a=a.responseStart,0<b&&a>=b&&(window.jstiming.srt=a-b));try{a=null,window.chrome&&window.chrome.csi&&(a=Math.floor(window.chrome.csi().pageT)),null==a&&
window.gtbExternal&&(a=window.gtbExternal.pageT()),null==a&&window.external&&(a=window.external.pageT),a&&(window.jstiming.pt=a)}catch(d){}})();})();

 
 
 
 
 var codesite_token = null;
 
 
 var CS_env = {"profileUrl": null, "domainName": null, "loggedInUserEmail": null, "token": null, "projectHomeUrl": "/p/goagent", "assetHostPath": "https://ssl.gstatic.com/codesite/ph", "relativeBaseUrl": "", "assetVersionPath": "https://ssl.gstatic.com/codesite/ph/8599073060794244502", "projectName": "goagent"};
 var _gaq = _gaq || [];
 _gaq.push(
 ['siteTracker._setAccount', 'UA-18071-1'],
 ['siteTracker._trackPageview']);
 
 (function() {
 var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
 ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
 (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
 })();
 
 </script>
 
 
 <title>Issue 1673 - 
 goagent -
 
 1.6.7和1.6.8 全都不能用了  Error code 502. - 
 https://github.com/goagent/goagent - Google Project Hosting
 </title>
 <link type="text/css" rel="stylesheet" href="https://ssl.gstatic.com/codesite/ph/8599073060794244502/css/core.css">
 
 <link type="text/css" rel="stylesheet" href="https://ssl.gstatic.com/codesite/ph/8599073060794244502/css/ph_detail.css" >
 
 
 
 
<!--[if IE]>
 <link type="text/css" rel="stylesheet" href="https://ssl.gstatic.com/codesite/ph/8599073060794244502/css/d_ie.css" >
<![endif]-->
 <style type="text/css">
 .menuIcon.off { background: no-repeat url(https://ssl.gstatic.com/codesite/ph/images/dropdown_sprite.gif) 0 -42px }
 .menuIcon.on { background: no-repeat url(https://ssl.gstatic.com/codesite/ph/images/dropdown_sprite.gif) 0 -28px }
 .menuIcon.down { background: no-repeat url(https://ssl.gstatic.com/codesite/ph/images/dropdown_sprite.gif) 0 0; }
 
 
 .attachments { width:33%; border-top:2px solid #999; padding-top: 3px; margin-left: .7em;}
 .attachments table { margin-bottom: 0.75em; }
 .attachments table tr td { padding: 0; margin: 0; font-size: 95%; }
 .preview { border: 2px solid #c3d9ff; padding: 1px; }
 .preview:hover { border: 2px solid blue; }
 .label { white-space: nowrap; }
 .derived { font-style:italic }
 .cursor_on .author {
 background: url(https://ssl.gstatic.com/codesite/ph/images/show-arrow.gif) no-repeat 2px;
 }
 .hiddenform {
 display: none;
 }

 
 </style>
</head>
<body class="t3">
<script type="text/javascript">
 window.___gcfg = {lang: 'en'};
 (function() 
 {var po = document.createElement("script");
 po.type = "text/javascript"; po.async = true;po.src = "https://apis.google.com/js/plusone.js";
 var s = document.getElementsByTagName("script")[0];
 s.parentNode.insertBefore(po, s);
 })();
</script>
<div class="headbg">

 <div id="gaia">
 

 <span>
 
 
 <a href="#" id="projects-dropdown" onclick="return false;"><u>My favorites</u> <small>&#9660;</small></a>
 | <a href="https://www.google.com/accounts/ServiceLogin?service=code&amp;ltmpl=phosting&amp;continue=https%3A%2F%2Fcode.google.com%2Fp%2Fgoagent%2Fissues%2Fdetail%3Fid%3D1673&amp;followup=https%3A%2F%2Fcode.google.com%2Fp%2Fgoagent%2Fissues%2Fdetail%3Fid%3D1673" onclick="_CS_click('/gb/ph/signin');"><u>Sign in</u></a>
 
 </span>

 </div>

 <div class="gbh" style="left: 0pt;"></div>
 <div class="gbh" style="right: 0pt;"></div>
 
 
 <div style="height: 1px"></div>
<!--[if lte IE 7]>
<div style="text-align:center;">
Your version of Internet Explorer is not supported. Try a browser that
contributes to open source, such as <a href="http://www.firefox.com">Firefox</a>,
<a href="http://www.google.com/chrome">Google Chrome</a>, or
<a href="http://code.google.com/chrome/chromeframe/">Google Chrome Frame</a>.
</div>
<![endif]-->



 <table style="padding:0px; margin: 0px 0px 10px 0px; width:100%" cellpadding="0" cellspacing="0"
 itemscope itemtype="http://schema.org/CreativeWork">
 <tr style="height: 58px;">
 
 
 
 <td id="plogo">
 <link itemprop="url" href="/p/goagent">
 <a href="/p/goagent/">
 
 <img src="https://ssl.gstatic.com/codesite/ph/images/defaultlogo.png" alt="Logo" itemprop="image">
 
 </a>
 </td>
 
 <td style="padding-left: 0.5em">
 
 <div id="pname">
 <a href="/p/goagent/"><span itemprop="name">goagent</span></a>
 </div>
 
 <div id="psum">
 <a id="project_summary_link"
 href="/p/goagent/"><span itemprop="description">https://github.com/goagent/goagent</span></a>
 
 </div>
 
 
 </td>
 <td style="white-space:nowrap;text-align:right; vertical-align:bottom;">
 
 <form action="/hosting/search">
 <input size="30" name="q" value="" type="text">
 
 <input type="submit" name="projectsearch" value="Search projects" >
 </form>
 
 </tr>
 </table>

</div>

 
<div id="mt" class="gtb"> 
 <a href="/p/goagent/" class="tab ">Project&nbsp;Home</a>
 
 
 
 
 
 
 
 
 <a href="/p/goagent/issues/list"
 class="tab active">Issues</a>
 
 
 
 
 
 
 
 
 
 
 <a href="https://code.google.com/export-to-github/export?project=goagent">
 <button>Export to GitHub</button>
 
 </a>
 
 
 
 
 
 <div class=gtbc></div>
</div>
<table cellspacing="0" cellpadding="0" width="100%" align="center" border="0" class="st">
 <tr>
 
 
 
 
 
 <td class="subt">
 <div class="issueDetail">
<div class="isf">
 
 
 <span class="inIssueEntry">
 <a class="buttonify" href="entry" onclick="return _newIssuePrompt();">New issue</a>
 </span> &nbsp;
 
 <span class="inIssueList">
 <span>Search</span>
 <form action="list" method="GET" style="display:inline">
 <select id="can" name="can">
 
<option disabled="disabled">Search within:</option>
<option value="1" >&nbsp;All issues</option>
<option value="2" selected=selected>&nbsp;Open issues</option>

<option value="6" >&nbsp;New issues</option>
<option value="7" >&nbsp;Issues to verify</option>

 </select>
 <span>for</span>
 <span id="qq"><input type="text" size="38" id="searchq" name="q"
 value="" autocomplete="off"
 
 onkeydown="_blurOnEsc(event)"></span>
 
 
 <span id="search_colspec"><input type="hidden" name="colspec" value="ID Opened Reporter Modified Summary Stars" ></span>
 
 
 
 <input type="hidden" name="cells" value="tiles" >
 <input type="submit" value="Search">
 </form>
 </span> &nbsp;
 <span class="inIssueAdvSearch">
 <a href="advsearch">Advanced search</a>
 </span> &nbsp;
 <span class="inIssueSearchTips">
 <a href="searchtips">Search tips</a>
 </span> &nbsp;
 <span class="inIssueSubscriptions">
 <a href="/p/goagent/issues/subscriptions">Subscriptions</a>
 </span>
</div>
</div>
 </td>
 
 
 
 
 <td align="right" valign="top" class="bevel-right"></td>
 </tr>
</table>


<script type="text/javascript">
 var cancelBubble = false;
 function _go(url) { document.location = url; }
</script>
<div id="maincol"
 
>

 






 

 

 

 


 

<div id="color_control" class="closed_colors">
<div id="issueheader">
<table cellpadding="0" cellspacing="0" width="100%"><tbody>
 <tr>
 <td class="vt h3" nowrap="nowrap" style="padding:0 5px">
 
 
 Issue <a href="detail?id=1673">1673</a>:
 </td>
 <td width="90%" class="vt">
 <span class="h3" >1.6.7和1.6.8 全都不能用了  Error code 502.</span>
 </td>
 <td>
 
 </td>
 </tr>
 <tr>
 <td></td>
 <td nowrap="nowrap">
 
 
 1 person starred this issue and may be notified of changes.
 
 
 
 </td>
 <td align="center" nowrap="nowrap">
 
 <a href="https://code.google.com/p/goagent/issues/list?cursor=goagent%3A1673">Back to list</a>
 
 </td>
 </tr>
 
</tbody></table>
</div>
<table width="100%" cellpadding="0" cellspacing="0" border="0" class="issuepage" id="meta-container">
<tbody class="collapse"> 
 <tr>
 <td id="issuemeta">
 <div id="meta-float">
 
<table cellspacing="0" cellpadding="0">
 <tr><th align="left">Status:&nbsp;</th>
 <td width="100%">
 
 <span title="The requested non-coding task was completed">Done</span>
 
 </td>
 </tr>
 
 
 
 
 <tr><th align="left">Owner:&nbsp;</th><td>
 
 
 ----
 
 
 </td>
 </tr>
 
 
 <tr><th align="left" valign="top">Closed:&nbsp;</th>
 <td align="left" valign="top" width="100%">
 Dec 2012
 </td>
 </tr>
 
 
 <tr><td colspan="2">
 
 
 
 <div style="padding-top:2px">
 
 <a href="list?q=label:Type-Defect"
 title="Report of a software defect"
 class="label"><b>Type-</b>Defect</a>
 
 </div>
 
 
 
 
 <div style="padding-top:2px">
 
 <a href="list?q=label:Priority-Medium"
 title="Normal priority"
 class="label"><b>Priority-</b>Medium</a>
 
 </div>
 
 
 </td></tr>
 
</table>
<div class="rel_issues">
 
 
 
</div>


 <br><br>
 
 
 <div style="white-space:nowrap"><a href="https://www.google.com/accounts/ServiceLogin?service=code&amp;ltmpl=phosting&amp;continue=https%3A%2F%2Fcode.google.com%2Fp%2Fgoagent%2Fissues%2Fdetail%3Fid%3D1673&amp;followup=https%3A%2F%2Fcode.google.com%2Fp%2Fgoagent%2Fissues%2Fdetail%3Fid%3D1673">Sign in</a> to add a comment</div>
 
 


 
 </div>&nbsp;
 </td>
 <td class="vt issuedescription" width="100%" id="cursorarea" >
 
<div class="cursor_off vt issuedescription" id="hc0">
 
 
 <div class="author">
 
 Reported by
 

 <a class="userlink"
 href="/u/115344437574074619995/">free...@gmail.com</a
>,
 <span class="date" title="Sat Nov 26 19:47:23 2011">Nov 26, 2011</span>
 
 </div>
<pre>

1.6.7 不知道从什么时候开始就什么网站都上不去了    今天更新了 1.6.8   还是不行    就是不能用了似的   不知道为什么    网页上提示为如下    无论上什么网全是这样的提示   
Error response

Error code 502.
Message: [&quot;MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 times!&quot;, &quot;MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 times!&quot;, &quot;MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 times!&quot;].

Error code explanation: 502 = Invalid responses from another server/proxy..


软件上提示是这样      有没有帮着看看是怎么回事   



  File &quot;httplib.pyo&quot;, line 951, in endheaders
  File &quot;httplib.pyo&quot;, line 811, in _send_output
  File &quot;httplib.pyo&quot;, line 773, in send
  File &quot;httplib.pyo&quot;, line 754, in connect
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 194, in socket_create_conn
ection
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 148, in __init__
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 179, in connect
RuntimeError: MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2',
 '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7',
 '203.208.46.8'):80 fail 3 times!
WARNING - - [27/Nov/2011 11:42:12] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
WARNING - - [27/Nov/2011 11:42:17] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
INFO - - [27/Nov/2011 11:42:17] urlfetch error=MultiplexConnection Connect hosts
 ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5'
, '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 times! on_error=&lt;bou
nd method LocalProxyHandler.handle_fetch_error of &lt;__main__.LocalProxyHandler in
stance at 0x01FCD1E8&gt;&gt;
WARNING - - [27/Nov/2011 11:42:17] LocalProxyHandler.handle_fetch_error Exceptio
n MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46
.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46
.8'):80 fail 3 times!
Traceback (most recent call last):
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 418, in urlfetch
  File &quot;urllib2.pyo&quot;, line 126, in urlopen
  File &quot;urllib2.pyo&quot;, line 394, in open
  File &quot;urllib2.pyo&quot;, line 412, in _open
  File &quot;urllib2.pyo&quot;, line 372, in _call_chain
  File &quot;urllib2.pyo&quot;, line 1199, in http_open
  File &quot;urllib2.pyo&quot;, line 1168, in do_open
  File &quot;httplib.pyo&quot;, line 955, in request
  File &quot;httplib.pyo&quot;, line 989, in _send_request
  File &quot;httplib.pyo&quot;, line 951, in endheaders
  File &quot;httplib.pyo&quot;, line 811, in _send_output
  File &quot;httplib.pyo&quot;, line 773, in send
  File &quot;httplib.pyo&quot;, line 754, in connect
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 194, in socket_create_conn
ection
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 148, in __init__
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 179, in connect
RuntimeError: MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2',
 '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7',
 '203.208.46.8'):80 fail 3 times!
WARNING - - [27/Nov/2011 11:42:19] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
WARNING - - [27/Nov/2011 11:42:24] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
WARNING - - [27/Nov/2011 11:42:24] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
WARNING - - [27/Nov/2011 11:42:29] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
INFO - - [27/Nov/2011 11:42:29] urlfetch error=MultiplexConnection Connect hosts
 ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5'
, '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 times! on_error=&lt;bou
nd method LocalProxyHandler.handle_fetch_error of &lt;__main__.LocalProxyHandler in
stance at 0x020FFCB0&gt;&gt;
WARNING - - [27/Nov/2011 11:42:29] LocalProxyHandler.handle_fetch_error Exceptio
n MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46
.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46
.8'):80 fail 3 times!
Traceback (most recent call last):
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 418, in urlfetch
  File &quot;urllib2.pyo&quot;, line 126, in urlopen
  File &quot;urllib2.pyo&quot;, line 394, in open
  File &quot;urllib2.pyo&quot;, line 412, in _open
  File &quot;urllib2.pyo&quot;, line 372, in _call_chain
  File &quot;urllib2.pyo&quot;, line 1199, in http_open
  File &quot;urllib2.pyo&quot;, line 1168, in do_open
  File &quot;httplib.pyo&quot;, line 955, in request
  File &quot;httplib.pyo&quot;, line 989, in _send_request
  File &quot;httplib.pyo&quot;, line 951, in endheaders
  File &quot;httplib.pyo&quot;, line 811, in _send_output
  File &quot;httplib.pyo&quot;, line 773, in send
  File &quot;httplib.pyo&quot;, line 754, in connect
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 194, in socket_create_conn
ection
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 148, in __init__
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 179, in connect
RuntimeError: MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2',
 '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7',
 '203.208.46.8'):80 fail 3 times!
WARNING - - [27/Nov/2011 11:42:29] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
127.0.0.1:55117 - - [27/Nov/2011 11:42:32] code 502, message [&quot;MultiplexConnecti
on Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4'
, '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 time
s!&quot;, &quot;MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.20
8.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.20
8.46.8'):80 fail 3 times!&quot;, &quot;MultiplexConnection Connect hosts ('203.208.46.1',
'203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6',
'203.208.46.7', '203.208.46.8'):80 fail 3 times!&quot;]
127.0.0.1:55117 - - [27/Nov/2011 11:42:32] &quot;GET <a href="https://accounts.youtube.com:443" rel="nofollow">https://accounts.youtube.com:443</a>
/accounts/CheckConnection?pmpo=https%3A%2F%2Faccounts.google.com&amp;v=1946930659 HT
TP/1.0&quot; 502 -
WARNING - - [27/Nov/2011 11:42:34] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
INFO - - [27/Nov/2011 11:42:34] urlfetch error=MultiplexConnection Connect hosts
 ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5'
, '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 times! on_error=&lt;bou
nd method LocalProxyHandler.handle_fetch_error of &lt;__main__.LocalProxyHandler in
stance at 0x01FCD1E8&gt;&gt;
WARNING - - [27/Nov/2011 11:42:34] LocalProxyHandler.handle_fetch_error Exceptio
n MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46
.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46
.8'):80 fail 3 times!
Traceback (most recent call last):
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 418, in urlfetch
  File &quot;urllib2.pyo&quot;, line 126, in urlopen
  File &quot;urllib2.pyo&quot;, line 394, in open
  File &quot;urllib2.pyo&quot;, line 412, in _open
  File &quot;urllib2.pyo&quot;, line 372, in _call_chain
  File &quot;urllib2.pyo&quot;, line 1199, in http_open
  File &quot;urllib2.pyo&quot;, line 1168, in do_open
  File &quot;httplib.pyo&quot;, line 955, in request
  File &quot;httplib.pyo&quot;, line 989, in _send_request
  File &quot;httplib.pyo&quot;, line 951, in endheaders
  File &quot;httplib.pyo&quot;, line 811, in _send_output
  File &quot;httplib.pyo&quot;, line 773, in send
  File &quot;httplib.pyo&quot;, line 754, in connect
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 194, in socket_create_conn
ection
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 148, in __init__
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 179, in connect
RuntimeError: MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2',
 '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7',
 '203.208.46.8'):80 fail 3 times!
127.0.0.1:55138 - - [27/Nov/2011 11:42:37] code 502, message [&quot;MultiplexConnecti
on Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4'
, '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 time
s!&quot;, &quot;MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.20
8.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.20
8.46.8'):80 fail 3 times!&quot;, &quot;MultiplexConnection Connect hosts ('203.208.46.1',
'203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6',
'203.208.46.7', '203.208.46.8'):80 fail 3 times!&quot;]
127.0.0.1:55138 - - [27/Nov/2011 11:42:37] &quot;GET <a href="https://accounts.youtube.com:443" rel="nofollow">https://accounts.youtube.com:443</a>
/accounts/CheckConnection?pmpo=https%3A%2F%2Faccounts.google.com&amp;v=2011942453 HT
TP/1.0&quot; 502 -
127.0.0.1:55272 - - [27/Nov/2011 11:44:05] &quot;CONNECT accounts.youtube.com:443 HTT
P/1.1&quot; 200 -
WARNING - - [27/Nov/2011 11:44:10] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
127.0.0.1:55289 - - [27/Nov/2011 11:44:11] &quot;GET <a href="http://autoproxy-gfwlist.googlec" rel="nofollow">http://autoproxy-gfwlist.googlec</a>
ode.com/svn/trunk/gfwlist.txt HTTP/1.1&quot; - -
WARNING - - [27/Nov/2011 11:44:15] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
WARNING - - [27/Nov/2011 11:44:16] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
WARNING - - [27/Nov/2011 11:44:20] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
INFO - - [27/Nov/2011 11:44:20] urlfetch error=MultiplexConnection Connect hosts
 ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5'
, '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 times! on_error=&lt;bou
nd method LocalProxyHandler.handle_fetch_error of &lt;__main__.LocalProxyHandler in
stance at 0x01FCBAA8&gt;&gt;
WARNING - - [27/Nov/2011 11:44:20] LocalProxyHandler.handle_fetch_error Exceptio
n MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46
.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46
.8'):80 fail 3 times!
Traceback (most recent call last):
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 418, in urlfetch
  File &quot;urllib2.pyo&quot;, line 126, in urlopen
  File &quot;urllib2.pyo&quot;, line 394, in open
  File &quot;urllib2.pyo&quot;, line 412, in _open
  File &quot;urllib2.pyo&quot;, line 372, in _call_chain
  File &quot;urllib2.pyo&quot;, line 1199, in http_open
  File &quot;urllib2.pyo&quot;, line 1168, in do_open
  File &quot;httplib.pyo&quot;, line 955, in request
  File &quot;httplib.pyo&quot;, line 989, in _send_request
  File &quot;httplib.pyo&quot;, line 951, in endheaders
  File &quot;httplib.pyo&quot;, line 811, in _send_output
  File &quot;httplib.pyo&quot;, line 773, in send
  File &quot;httplib.pyo&quot;, line 754, in connect
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 194, in socket_create_conn
ection
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 148, in __init__
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 179, in connect
RuntimeError: MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2',
 '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7',
 '203.208.46.8'):80 fail 3 times!
WARNING - - [27/Nov/2011 11:44:21] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
WARNING - - [27/Nov/2011 11:44:26] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
WARNING - - [27/Nov/2011 11:44:26] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
ERROR - - [27/Nov/2011 11:44:26] LocalProxyHandler.do_GET Error, MultiplexConnec
tion Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.
4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 ti
mes!
Traceback (most recent call last):
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 740, in do_METHOD_Direct
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 148, in __init__
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 179, in connect
RuntimeError: MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2',
 '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7',
 '203.208.46.8'):80 fail 3 times!
WARNING - - [27/Nov/2011 11:44:31] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
WARNING - - [27/Nov/2011 11:44:36] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
INFO - - [27/Nov/2011 11:44:36] urlfetch error=MultiplexConnection Connect hosts
 ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5'
, '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 times! on_error=&lt;bou
nd method LocalProxyHandler.handle_fetch_error of &lt;__main__.LocalProxyHandler in
stance at 0x01FCBAA8&gt;&gt;
WARNING - - [27/Nov/2011 11:44:36] LocalProxyHandler.handle_fetch_error Exceptio
n MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46
.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46
.8'):80 fail 3 times!
Traceback (most recent call last):
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 418, in urlfetch
  File &quot;urllib2.pyo&quot;, line 126, in urlopen
  File &quot;urllib2.pyo&quot;, line 394, in open
  File &quot;urllib2.pyo&quot;, line 412, in _open
  File &quot;urllib2.pyo&quot;, line 372, in _call_chain
  File &quot;urllib2.pyo&quot;, line 1199, in http_open
  File &quot;urllib2.pyo&quot;, line 1168, in do_open
  File &quot;httplib.pyo&quot;, line 955, in request
  File &quot;httplib.pyo&quot;, line 989, in _send_request
  File &quot;httplib.pyo&quot;, line 951, in endheaders
  File &quot;httplib.pyo&quot;, line 811, in _send_output
  File &quot;httplib.pyo&quot;, line 773, in send
  File &quot;httplib.pyo&quot;, line 754, in connect
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 194, in socket_create_conn
ection
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 148, in __init__
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 179, in connect
RuntimeError: MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2',
 '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7',
 '203.208.46.8'):80 fail 3 times!
WARNING - - [27/Nov/2011 11:44:43] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
WARNING - - [27/Nov/2011 11:44:48] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
WARNING - - [27/Nov/2011 11:44:53] MultiplexConnection Cannot hosts ('203.208.46
.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46
.6', '203.208.46.7', '203.208.46.8'):80, window=8
INFO - - [27/Nov/2011 11:44:53] urlfetch error=MultiplexConnection Connect hosts
 ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5'
, '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 times! on_error=&lt;bou
nd method LocalProxyHandler.handle_fetch_error of &lt;__main__.LocalProxyHandler in
stance at 0x01FCBAA8&gt;&gt;
WARNING - - [27/Nov/2011 11:44:53] LocalProxyHandler.handle_fetch_error Exceptio
n MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46
.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46
.8'):80 fail 3 times!
Traceback (most recent call last):
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 418, in urlfetch
  File &quot;urllib2.pyo&quot;, line 126, in urlopen
  File &quot;urllib2.pyo&quot;, line 394, in open
  File &quot;urllib2.pyo&quot;, line 412, in _open
  File &quot;urllib2.pyo&quot;, line 372, in _call_chain
  File &quot;urllib2.pyo&quot;, line 1199, in http_open
  File &quot;urllib2.pyo&quot;, line 1168, in do_open
  File &quot;httplib.pyo&quot;, line 955, in request
  File &quot;httplib.pyo&quot;, line 989, in _send_request
  File &quot;httplib.pyo&quot;, line 951, in endheaders
  File &quot;httplib.pyo&quot;, line 811, in _send_output
  File &quot;httplib.pyo&quot;, line 773, in send
  File &quot;httplib.pyo&quot;, line 754, in connect
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 194, in socket_create_conn
ection
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 148, in __init__
  File &quot;D:\phus-goagent-9d03fff\local\proxy.py&quot;, line 179, in connect
RuntimeError: MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2',
 '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7',
 '203.208.46.8'):80 fail 3 times!
127.0.0.1:55272 - - [27/Nov/2011 11:44:56] code 502, message [&quot;MultiplexConnecti
on Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4'
, '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 time
s!&quot;, &quot;MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.20
8.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.20
8.46.8'):80 fail 3 times!&quot;, &quot;MultiplexConnection Connect hosts ('203.208.46.1',
'203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6',
'203.208.46.7', '203.208.46.8'):80 fail 3 times!&quot;]
127.0.0.1:55272 - - [27/Nov/2011 11:44:56] &quot;GET <a href="https://accounts.youtube.com:443" rel="nofollow">https://accounts.youtube.com:443</a>
/accounts/CheckConnection?pmpo=https%3A%2F%2Faccounts.google.com&amp;v=1733250957 HT
TP/1.0&quot; 502 -

</pre>

</div>

 


 
 
 
 
 <div class="cursor_off vt issuecomment"
 id="hc1">
 <div style="float:right; margin-right:.3em; text-align:right">
 <span class="date" title="Sun Nov 27 01:25:31 2011">
 Nov 27, 2011
 </span>
 
 
 
 </div>
 
 
 
 
 
 
 
 
 
 
 <span class="author">
 
 <a name="c1" href="/p/goagent/issues/detail?id=1673#c1">#1</a>
 

 <a class="userlink"
 href="/u/anyliz.zhy/">anyliz.zhy</a
></span>
 
<pre>
同样的问题哦
</pre>
 
 
 </div>
 

 
 
 
 
 <div class="cursor_off vt issuecomment"
 id="hc2">
 <div style="float:right; margin-right:.3em; text-align:right">
 <span class="date" title="Mon Nov 28 08:59:07 2011">
 Nov 28, 2011
 </span>
 
 
 
 </div>
 
 
 
 
 
 
 
 
 
 
 <span class="author">
 
 <a name="c2" href="/p/goagent/issues/detail?id=1673#c2">#2</a>
 

 <a class="userlink"
 href="/u/102462394354599940867/">SFYSt...@gmail.com</a
></span>
 
<pre>
1.6.9, 502.
INFO - - [29/Nov/2011 00:49:47] PHPProxyHandler.setup check goagentp.sinaapp.com is in common.HOSTS
INFO - - [29/Nov/2011 00:49:47] Resole php fetchserver address.
INFO - - [29/Nov/2011 00:49:47] Resole php fetchserver address OK. 202.108.5.19
INFO - - [29/Nov/2011 00:49:47] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x83605cc&gt;&gt;
ERROR - - [29/Nov/2011 00:49:47] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
INFO - - [29/Nov/2011 00:49:48] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x83605cc&gt;&gt;
ERROR - - [29/Nov/2011 00:49:48] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
INFO - - [29/Nov/2011 00:49:50] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x83605cc&gt;&gt;
ERROR - - [29/Nov/2011 00:49:50] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
127.0.0.1:50231 - - [29/Nov/2011 00:49:53] code 502, message ['HTTP Error 600: domain_not_exists', 'HTTP Error 600: domain_not_exists', 'HTTP Error 600: domain_not_exists']
127.0.0.1:50231 - - [29/Nov/2011 00:49:53] &quot;GET <a href="http://www.baidu.com/" rel="nofollow">http://www.baidu.com/</a> HTTP/1.1&quot; 502 -
127.0.0.1:50248 - - [29/Nov/2011 00:50:18] &quot;CONNECT www.google.com:443 HTTP/1.1&quot; 200 -
ERROR - - [29/Nov/2011 00:50:18] do_CONNECT_Thunnel socket.error: [Errno 1] _ssl.c:499: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;./proxy.py&quot;, line 694, in do_CONNECT_Thunnel
    self.connection = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/usr/lib/python2.7/ssl.py&quot;, line 344, in wrap_socket
    ciphers=ciphers)
  File &quot;/usr/lib/python2.7/ssl.py&quot;, line 121, in __init__
    self.do_handshake()
  File &quot;/usr/lib/python2.7/ssl.py&quot;, line 283, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:499: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50248)
Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/SocketServer.py&quot;, line 582, in process_request_thread
    self.finish_request(request, client_address)
  File &quot;/usr/lib/python2.7/SocketServer.py&quot;, line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File &quot;/usr/lib/python2.7/SocketServer.py&quot;, line 639, in __init__
    self.handle()
  File &quot;/usr/lib/python2.7/BaseHTTPServer.py&quot;, line 337, in handle
    self.handle_one_request()
  File &quot;/usr/lib/python2.7/BaseHTTPServer.py&quot;, line 325, in handle_one_request
    method()
  File &quot;./proxy.py&quot;, line 708, in do_CONNECT_Thunnel
    self.connection.shutdown(socket.SHUT_WR)
  File &quot;/usr/lib/python2.7/socket.py&quot;, line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected
----------------------------------------
127.0.0.1:50249 - - [29/Nov/2011 00:50:21] &quot;CONNECT www.google.com:443 HTTP/1.1&quot; 200 -
ERROR - - [29/Nov/2011 00:50:21] do_CONNECT_Thunnel socket.error: [Errno 1] _ssl.c:499: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;./proxy.py&quot;, line 694, in do_CONNECT_Thunnel
    self.connection = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/usr/lib/python2.7/ssl.py&quot;, line 344, in wrap_socket
    ciphers=ciphers)
  File &quot;/usr/lib/python2.7/ssl.py&quot;, line 121, in __init__
    self.do_handshake()
  File &quot;/usr/lib/python2.7/ssl.py&quot;, line 283, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:499: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
127.0.0.1:50250 - - [29/Nov/2011 00:50:21] &quot;CONNECT www.google.com:443 HTTP/1.1&quot; 200 -
INFO - - [29/Nov/2011 00:50:21] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x83603ec&gt;&gt;
ERROR - - [29/Nov/2011 00:50:21] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
INFO - - [29/Nov/2011 00:50:23] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x83603ec&gt;&gt;
ERROR - - [29/Nov/2011 00:50:23] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
INFO - - [29/Nov/2011 00:50:25] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x83603ec&gt;&gt;
ERROR - - [29/Nov/2011 00:50:25] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
127.0.0.1:50250 - - [29/Nov/2011 00:50:28] code 502, message ['HTTP Error 600: domain_not_exists', 'HTTP Error 600: domain_not_exists', 'HTTP Error 600: domain_not_exists']
127.0.0.1:50250 - - [29/Nov/2011 00:50:28] &quot;GET <a href="https://www.google.com:443/search?q=python+appcfg.zip+update+.%2F&amp;ie=utf-8&amp;oe=utf-8&amp;aq=t&amp;rls=org.mozilla:en-US:unofficial&amp;client=firefox-a" rel="nofollow">https://www.google.com:443/search?q=python+appcfg.zip+update+.%2F&amp;ie=utf-8&amp;oe=utf-8&amp;aq=t&amp;rls=org.mozilla:en-US:unofficial&amp;client=firefox-a</a> HTTP/1.0&quot; 502 -
INFO - - [29/Nov/2011 00:50:32] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x836074c&gt;&gt;
ERROR - - [29/Nov/2011 00:50:32] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
INFO - - [29/Nov/2011 00:50:33] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x836074c&gt;&gt;
ERROR - - [29/Nov/2011 00:50:33] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
INFO - - [29/Nov/2011 00:50:35] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x836074c&gt;&gt;
ERROR - - [29/Nov/2011 00:50:35] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
127.0.0.1:50254 - - [29/Nov/2011 00:50:38] code 502, message ['HTTP Error 600: domain_not_exists', 'HTTP Error 600: domain_not_exists', 'HTTP Error 600: domain_not_exists']
127.0.0.1:50254 - - [29/Nov/2011 00:50:38] &quot;GET <a href="http://www.google.com/search?q=python+appcfg.zip+update+.%2F&amp;ie=utf-8&amp;oe=utf-8&amp;aq=t&amp;rls=org.mozilla:en-US:unofficial&amp;client=firefox-a" rel="nofollow">http://www.google.com/search?q=python+appcfg.zip+update+.%2F&amp;ie=utf-8&amp;oe=utf-8&amp;aq=t&amp;rls=org.mozilla:en-US:unofficial&amp;client=firefox-a</a> HTTP/1.1&quot; 502 -
INFO - - [29/Nov/2011 00:50:39] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x836082c&gt;&gt;
ERROR - - [29/Nov/2011 00:50:39] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
INFO - - [29/Nov/2011 00:50:40] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x836082c&gt;&gt;
ERROR - - [29/Nov/2011 00:50:40] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
INFO - - [29/Nov/2011 00:50:42] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x836082c&gt;&gt;
ERROR - - [29/Nov/2011 00:50:42] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
127.0.0.1:50260 - - [29/Nov/2011 00:50:45] code 502, message ['HTTP Error 600: domain_not_exists', 'HTTP Error 600: domain_not_exists', 'HTTP Error 600: domain_not_exists']
127.0.0.1:50260 - - [29/Nov/2011 00:50:45] &quot;GET <a href="http://www.baidu.com/" rel="nofollow">http://www.baidu.com/</a> HTTP/1.1&quot; 502 -
INFO - - [29/Nov/2011 00:51:36] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x836080c&gt;&gt;
ERROR - - [29/Nov/2011 00:51:36] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
INFO - - [29/Nov/2011 00:51:37] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x836080c&gt;&gt;
ERROR - - [29/Nov/2011 00:51:37] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
INFO - - [29/Nov/2011 00:51:38] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x839f84c&gt;&gt;
ERROR - - [29/Nov/2011 00:51:38] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
INFO - - [29/Nov/2011 00:51:39] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x836080c&gt;&gt;
ERROR - - [29/Nov/2011 00:51:39] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
INFO - - [29/Nov/2011 00:51:39] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x839f84c&gt;&gt;
ERROR - - [29/Nov/2011 00:51:39] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
INFO - - [29/Nov/2011 00:51:42] urlfetch error=HTTP Error 600: domain_not_exists on_error=&lt;bound method PHPProxyHandler.handle_fetch_error of &lt;__main__.PHPProxyHandler instance at 0x839f84c&gt;&gt;
ERROR - - [29/Nov/2011 00:51:42] PHPProxyHandler handle_fetch_error HTTP Error 600: domain_not_exists
127.0.0.1:50268 - - [29/Nov/2011 00:51:42] code 502, message ['HTTP Error 600: domain_not_exists', 'HTTP Error 600: domain_not_exists', 'HTTP Error 600: domain_not_exists']
127.0.0.1:50268 - - [29/Nov/2011 00:51:42] &quot;GET <a href="http://www.google.com/search?q=python+appcfg.zip+update+.%2F&amp;ie=utf-8&amp;oe=utf-8&amp;aq=t&amp;rls=org.mozilla:en-US:unofficial&amp;client=firefox-a" rel="nofollow">http://www.google.com/search?q=python+appcfg.zip+update+.%2F&amp;ie=utf-8&amp;oe=utf-8&amp;aq=t&amp;rls=org.mozilla:en-US:unofficial&amp;client=firefox-a</a> HTTP/1.1&quot; 502 -
127.0.0.1:50271 - - [29/Nov/2011 00:51:45] code 502, message ['HTTP Error 600: domain_not_exists', 'HTTP Error 600: domain_not_exists', 'HTTP Error 600: domain_not_exists']

</pre>
 
 
 </div>
 

 
 
 
 
 <div class="cursor_off vt issuecomment"
 id="hc3">
 <div style="float:right; margin-right:.3em; text-align:right">
 <span class="date" title="Sat Dec 15 18:07:08 2012">
 Dec 15, 2012
 </span>
 
 
 
 </div>
 
 
 
 
 
 
 
 
 
 
 <span class="author">
 
 <a name="c3" href="/p/goagent/issues/detail?id=1673#c3">#3</a>
 

 <a class="userlink"
 href="/u/wwqgtxx/">wwqgtxx</a
></span>
 
<pre>
<i>(No comment was entered for this change.)</i>
</pre>
 
 
 <div class="updates">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 
 <b>Status:</b>
 Done
 
 <br>
 
 </div>
 <div class="round1"></div>
 <div class="round2"></div>
 <div class="round4"></div>
 </div>
 
 </div>
 

 
 
 
 
 <div class="cursor_off vt issuecomment"
 id="hc4">
 <div style="float:right; margin-right:.3em; text-align:right">
 <span class="date" title="Thu Jan 10 14:06:07 2013">
 Jan 10, 2013
 </span>
 
 
 
 </div>
 
 
 
 
 
 
 
 
 
 
 <span class="author">
 
 <a name="c4" href="/p/goagent/issues/detail?id=1673#c4">#4</a>
 

 <a class="userlink"
 href="/u/116839838720113220100/">modch...@gmail.com</a
></span>
 
<pre>
Error code 502.

Message: [&quot;MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 times!&quot;, &quot;MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 times!&quot;, &quot;MultiplexConnection Connect hosts ('203.208.46.1', '203.208.46.2', '203.208.46.3', '203.208.46.4', '203.208.46.5', '203.208.46.6', '203.208.46.7', '203.208.46.8'):80 fail 3 times!&quot;].

Error code explanation: 502 = Invalid responses from another server/proxy..

我也是，ipad2 safari浏览器无法访问youtube啊。
</pre>
 
 
 </div>
 


 


 </td>
 </tr>

 
 <tr>
 <td></td>
 <td class="vt issuecomment">
 <span class="indicator">&#9658;</span> <a href="https://www.google.com/accounts/ServiceLogin?service=code&ltmpl=phosting&continue=https%3A%2F%2Fcode.google.com%2Fp%2Fgoagent%2Fissues%2Fdetail%3Fid%3D1673&amp;followup=https%3A%2F%2Fcode.google.com%2Fp%2Fgoagent%2Fissues%2Fdetail%3Fid%3D1673"
 >Sign in</a> to add a comment
 </td>
 </tr>
 

</tbody>
</table>
<br>
<script type="text/javascript" src="https://ssl.gstatic.com/codesite/ph/8599073060794244502/js/dit_scripts.js"></script>



 

</div> 
<form name="delcom" action="delComment.do?q=&amp;can=2&amp;groupby=&amp;sort=&amp;colspec=ID+Opened+Reporter+Modified+Summary+Stars" method="POST">
 <input type="hidden" name="sequence_num" value="">
 <input type="hidden" name="mode" value="">
 <input type="hidden" name="id" value="1673">
 <input type="hidden" name="token" value="">
</form>

<div id="helparea"></div>
<script type="text/javascript">
 _onload();
 function delComment(sequence_num, delete_mode) {
 var f = document.forms["delcom"];
 f.sequence_num.value = sequence_num;
 f.mode.value = delete_mode;
 
 f.submit();
 return false;
 }
 
 _floatMetadata();
</script>
<script type="text/javascript" src="https://ssl.gstatic.com/codesite/ph/8599073060794244502/js/kibbles.js"></script>
<script type="text/javascript">
 _setupKibblesOnDetailPage(
 'https://code.google.com/p/goagent/issues/list?cursor\x3dgoagent%3A1673',
 '/p/goagent/issues/entry',
 '',
 '',
 '', 'goagent', 1673,
 false, false, codesite_token);
</script>
 
 
 
 <script type="text/javascript" src="https://ssl.gstatic.com/codesite/ph/8599073060794244502/js/ph_core.js"></script>
 
 
 
 
</div> 

<div id="footer" dir="ltr">
 <div class="text">
 <a href="/projecthosting/terms.html">Terms</a> -
 <a href="http://www.google.com/privacy.html">Privacy</a> -
 <a href="/p/support/">Project Hosting Help</a>
 </div>
</div>
 <div class="hostedBy" style="margin-top: -20px;">
 <span style="vertical-align: top;">Powered by <a href="http://code.google.com/projecthosting/">Google Project Hosting</a></span>
 </div>

 
 


 
 
 <script type="text/javascript">_CS_reportToCsi();</script>
 
 </body>
</html>

