------------------------------------------------------
GoAgent Version    : 3.0.5 (python/2.7.5 gevent/1.0dev pyopenssl/0.13)
Listen Address     : 192.168.8.10:8087
Local Proxy        : 127.0.0.1:8087
GAE Mode           : https
GAE Profile        : google_cn
GAE APPID          : app4mavenp1
Pac Server         : http://192.168.8.10:8086/proxy.pac
Pac File           : file://D:/Programe Files/goagent-3.0.4_65b9542b98d2/local/proxy.pac
------------------------------------------------------
ERROR - [Sep 23 14:42:29] create_connection_withproxy error [Errno 10061] 由于目标计算机积极拒绝，无法连接。
ERROR - [Sep 23 14:42:30] create_connection_withproxy error [Errno 10061] 由于目标计算机积极拒绝，无法连接。
ERROR - [Sep 23 14:42:31] create_connection_withproxy error [Errno 10061] 由于目标计算机积极拒绝，无法连接。
ERROR - [Sep 23 14:42:32] create_connection_withproxy error [Errno 10061] 由于目标计算机积极拒绝，无法连接。
ERROR - [Sep 23 14:42:32] GAEProxyHandler.do_METHOD_GAE 'http://www.hao123.com/?tn=98012088_2_hao_pg' return error(10061, '\xd3\xc9\xd3\xda\xc4\xbf\xb1\xea\xbc\xc6\xcb\xe3\xbb\xfa\xbb\xfd\xbc\xab\xbe\xdc\xbe\xf8\xa3\xac\
xce\xde\xb7\xa8\xc1\xac\xbd\xd3\xa1\xa3'), try again
Traceback (most recent call last):
  File "proxy.py", line 1944, in do_METHOD_GAE
  File "proxy.py", line 1495, in gae_urlfetch
  File "proxy.py", line 1267, in request
  File "proxy.py", line 1108, in create_connection_withproxy
  File "D:\Programe Files\goagent-3.0.4_65b9542b98d2\local\python27.zip\gevent\socket.py", line 591, in create_connection
error: [Errno 10061] 由于目标计算机积极拒绝，无法连接。
ERROR - [Sep 23 14:42:33] create_connection_withproxy error [Errno 10061] 由于目标计算机积极拒绝，无法连接。
ERROR - [Sep 23 14:42:34] create_connection_withproxy error [Errno 10061] 由于目标计算机积极拒绝，无法连接。
ERROR - [Sep 23 14:42:35] create_connection_withproxy error [Errno 10061] 由于目标计算机积极拒绝，无法连接。
ERROR - [Sep 23 14:42:36] create_connection_withproxy error [Errno 10061] 由于目标计算机积极拒绝，无法连接。
ERROR - [Sep 23 14:42:36] GAEProxyHandler.do_METHOD_GAE 'http://www.hao123.com/?tn=98012088_2_hao_pg' return error(10061, '\xd3\xc9\xd3\xda\xc4\xbf\xb1\xea\xbc\xc6\xcb\xe3\xbb\xfa\xbb\xfd\xbc\xab\xbe\xdc\xbe\xf8\xa3\xac\
xce\xde\xb7\xa8\xc1\xac\xbd\xd3\xa1\xa3'), try again
Traceback (most recent call last):
  File "proxy.py", line 1944, in do_METHOD_GAE
  File "proxy.py", line 1495, in gae_urlfetch
  File "proxy.py", line 1267, in request
  File "proxy.py", line 1108, in create_connection_withproxy
  File "D:\Programe Files\goagent-3.0.4_65b9542b98d2\local\python27.zip\gevent\socket.py", line 591, in create_connection
error: [Errno 10061] 由于目标计算机积极拒绝，无法连接。
ERROR - [Sep 23 14:42:37] create_connection_withproxy error [Errno 10061] 由于目标计算机积极拒绝，无法连接。
ERROR - [Sep 23 14:42:38] create_connection_withproxy error [Errno 10061] 由于目标计算机积极拒绝，无法连接。
ERROR - [Sep 23 14:42:39] create_connection_withproxy error [Errno 10061] 由于目标计算机积极拒绝，无法连接。
ERROR - [Sep 23 14:42:40] create_connection_withproxy error [Errno 10061] 由于目标计算机积极拒绝，无法连接。
ERROR - [Sep 23 14:42:40] GAEProxyHandler.do_METHOD_GAE 'http://www.hao123.com/?tn=98012088_2_hao_pg' return error(10061, '\xd3\xc9\xd3\xda\xc4\xbf\xb1\xea\xbc\xc6\xcb\xe3\xbb\xfa\xbb\xfd\xbc\xab\xbe\xdc\xbe\xf8\xa3\xac\
xce\xde\xb7\xa8\xc1\xac\xbd\xd3\xa1\xa3'), try again
Traceback (most recent call last):
  File "proxy.py", line 1944, in do_METHOD_GAE
  File "proxy.py", line 1495, in gae_urlfetch
  File "proxy.py", line 1267, in request
  File "proxy.py", line 1108, in create_connection_withproxy
  File "D:\Programe Files\goagent-3.0.4_65b9542b98d2\local\python27.zip\gevent\socket.py", line 591, in create_connection
error: [Errno 10061] 由于目标计算机积极拒绝，无法连接。
