Google App Engine </>

  * *我的gae名字@gmail.com * |
  * My Account <https://www.google.com/accounts/ManageAccount> |
  * Help <http://code.google.com/appengine/kb/> |
  * Sign out
    <https://appengine.google.com/_ah/logout?continue=https://www.google.com/accounts/Logout%3Fcontinue%3Dhttps://appengine.google.com/_ah/logout%253Fcontinue%253Dhttps://appengine.google.com/start%26service%3Dah>


Application:

: 1

« My Applications </>

  * Main
      o Dashboard
        </dashboard?&app_id=s~我的gae名字&version_id=1.351254833983301283>
      o Instances
        </instances?&app_id=s~我的gae名字&version_id=1.351254833983301283>
      o Logs </logs?&app_id=s~我的gae名字&version_id=1.351254833983301283>
      o Versions
        </deployment?&app_id=s~我的gae名字&version_id=1.351254833983301283>
      o Backends
        </backends?&app_id=s~我的gae名字&version_id=1.351254833983301283>
      o Cron Jobs
        </cron?&app_id=s~我的gae名字&version_id=1.351254833983301283>
      o Task Queues
        </queues?&app_id=s~我的gae名字&version_id=1.351254833983301283>
      o Quota Details
        </dashboard/quotadetails?&app_id=s~我的gae名字&version_id=1.351254833983301283>

  * Data
      o Datastore Indexes
        </datastore/indexes?&app_id=s~我的gae名字&version_id=1.351254833983301283>

      o Datastore Viewer
        </datastore/explorer?&app_id=s~我的gae名字&version_id=1.351254833983301283>

      o Datastore Statistics
        </datastore/statistics?&app_id=s~我的gae名字&version_id=1.351254833983301283>

      o Blob Viewer
        </blobstore/explorer?&app_id=s~我的gae名字&version_id=1.351254833983301283>

      o Prospective Search
        </prospective_search/subscriptions?&app_id=s~我的gae名字&version_id=1.351254833983301283>

      o Datastore Admin
        </datastore/admin?&app_id=s~我的gae名字&version_id=1.351254833983301283>

  * Administration
      o Application Settings
        </settings?&app_id=s~我的gae名字&version_id=1.351254833983301283>
      o Permissions
        </permissions?&app_id=s~我的gae名字&version_id=1.351254833983301283>
      o Blacklist
        </blacklist?&app_id=s~我的gae名字&version_id=1.351254833983301283>
      o Admin Logs
        </adminlogs?&app_id=s~我的gae名字&version_id=1.351254833983301283>
  * Billing
      o Billing Settings
        </billing/settings?&app_id=s~我的gae名字&version_id=1.351254833983301283>

      o Billing History
        </billing/history?&app_id=s~我的gae名字&version_id=1.351254833983301283>



        Resources

  * Documentation <http://code.google.com/appengine>
  * FAQ <http://code.google.com/appengine/kb/>
  * Developer Forum <http://groups.google.com/group/google-appengine>
  * Downloads <http://code.google.com/appengine/downloads.html>
  * System Status <http://code.google.com/status/appengine>

Show:
All requests Logs with minimum severity: Timezone:
Options
Filter:
Regex Labels
Regex filters are case-sensitive regular expressions
<http://www.python.org/doc/2.5.2/lib/re-syntax.html>, e.g.
/^[tT]raceback/ or /hello.*rld/
Labels are regular expressions
<http://www.python.org/doc/2.5.2/lib/re-syntax.html> for filtering
Apache Combined logs
<http://httpd.apache.org/docs/1.3/logs.html#combined> by logging fields.
Valid labels:

  * day,
  * month,
  * year,
  * hour,
  * minute,
  * second,
  * tzone,
  * remotehost,
  * identd_user,
  * user,
  * status,
  * bytes,
  * referrer,
  * useragent,
  * method,
  * path,
  * querystring,
  * protocol,
  * request_id_hash

e.g. /path:/foo.* useragent:.*Chrome.*/ - all requests to a path
starting with /foo from the Chrome browser.
Since:
Now
Rows:

*Tip:* Click a log line to show or hide its details.
Collapse logs

 1.
    ‹ Prev 20 *1-20 * Next 20 ›
    </logs?app_id=s~我的gae名字&version_id=1.351254833983301283&offset=0004A5F74B641CCF.C7DA6EE3&start_index=21>
    (Top: 1 day, 22:57:43 ago)
 2.
     1.


                  2011-06-18 03:13:26.136 /fetch.py 500 30116ms 35cpu_ms
                  0kb gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9C0C0B393.87AB6BB1&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:13:26 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30116 cpu_ms=36 api_cpu_ms=0 cpm_usd=0.001443 exit_code=104

     2.


                  E 2011-06-18 03:13:25.695
                  DeadlineExceededError(deadline=30,
                  url='http://0.50.channel.facebook.com/x/2796044913/1355509675/true/p_100001775137056=1')


     3.


                  E 2011-06-18 03:13:26.127 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

 3.
     1.


                  2011-06-18 03:13:26.136 /fetch.py 500 30116ms 35cpu_ms
                  0kb gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9C0C0B393.87AB6BB1&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:13:26 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30116 cpu_ms=36 api_cpu_ms=0 cpm_usd=0.001443 exit_code=104

     2.


                  E 2011-06-18 03:13:25.695

        DeadlineExceededError(deadline=30, url='http://0.50.channel.facebook.com/x/2796044913/1355509675/true/p_100001775137056=1')

     3.


                  E 2011-06-18 03:13:26.127

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 03:13:26.130

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

 4.
     1.


                  2011-06-18 03:12:44.342 /fetch.py 500 30061ms 36cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9BE42FA1B.1622C2CB&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:12:44 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30061 cpu_ms=37 api_cpu_ms=0 cpm_usd=0.001558 exit_code=104

     2.


                  E 2011-06-18 03:12:43.930
                  DeadlineExceededError(deadline=30,
                  url='http://0.50.channel.facebook.com/x/3824020909/1355509675/false/p_100001775137056=1')


     3.


                  E 2011-06-18 03:12:44.331 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

 5.
     1.


                  2011-06-18 03:12:44.342 /fetch.py 500 30061ms 36cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9BE42FA1B.1622C2CB&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:12:44 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30061 cpu_ms=37 api_cpu_ms=0 cpm_usd=0.001558 exit_code=104

     2.


                  E 2011-06-18 03:12:43.930

        DeadlineExceededError(deadline=30, url='http://0.50.channel.facebook.com/x/3824020909/1355509675/false/p_100001775137056=1')

     3.


                  E 2011-06-18 03:12:44.331

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 03:12:44.334

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

 6.
     1.


                  2011-06-18 03:12:14.017 /fetch.py 500 30037ms 35cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9BC744021.19482E3C&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:12:14 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30037 cpu_ms=36 api_cpu_ms=0 cpm_usd=0.001535 exit_code=104

     2.


                  E 2011-06-18 03:12:13.711
                  DeadlineExceededError(deadline=30,
                  url='http://0.50.channel.facebook.com/x/3824020909/1355509675/false/p_100001775137056=1')


     3.


                  E 2011-06-18 03:12:14.007 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

 7.
     1.


                  2011-06-18 03:12:14.017 /fetch.py 500 30037ms 35cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9BC744021.19482E3C&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:12:14 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30037 cpu_ms=36 api_cpu_ms=0 cpm_usd=0.001535 exit_code=104

     2.


                  E 2011-06-18 03:12:13.711

        DeadlineExceededError(deadline=30, url='http://0.50.channel.facebook.com/x/3824020909/1355509675/false/p_100001775137056=1')

     3.


                  E 2011-06-18 03:12:14.007

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 03:12:14.010

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

 8.
     1.


                  2011-06-18 03:10:06.399 /fetch.py 500 30055ms 35cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9B4D8F5DB.732AD3CC&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:10:06 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30056 cpu_ms=36 api_cpu_ms=0 cpm_usd=0.001535 exit_code=104

     2.


                  E 2011-06-18 03:10:05.960
                  DeadlineExceededError(deadline=30,
                  url='http://0.50.channel.facebook.com/x/1767090220/1355509675/false/p_100001775137056=1')


     3.


                  E 2011-06-18 03:10:06.392 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

 9.
     1.


                  2011-06-18 03:10:06.399 /fetch.py 500 30055ms 35cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9B4D8F5DB.732AD3CC&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:10:06 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30056 cpu_ms=36 api_cpu_ms=0 cpm_usd=0.001535 exit_code=104

     2.


                  E 2011-06-18 03:10:05.960

        DeadlineExceededError(deadline=30, url='http://0.50.channel.facebook.com/x/1767090220/1355509675/false/p_100001775137056=1')

     3.


                  E 2011-06-18 03:10:06.392

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 03:10:06.398

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

10.
     1.


                  2011-06-18 03:09:36.078 /fetch.py 500 30275ms 17cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9B30A499B.01108FBC&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:09:36 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30275 cpu_ms=18 api_cpu_ms=0 cpm_usd=0.001026 exit_code=104

     2.


                  E 2011-06-18 03:09:35.465
                  DeadlineExceededError(deadline=30,
                  url='http://0.50.channel.facebook.com/x/1767090220/1355509675/false/p_100001775137056=1')


     3.


                  E 2011-06-18 03:09:36.066 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

11.
     1.


                  2011-06-18 03:09:36.078 /fetch.py 500 30275ms 17cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9B30A499B.01108FBC&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:09:36 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30275 cpu_ms=18 api_cpu_ms=0 cpm_usd=0.001026 exit_code=104

     2.


                  E 2011-06-18 03:09:35.465

        DeadlineExceededError(deadline=30, url='http://0.50.channel.facebook.com/x/1767090220/1355509675/false/p_100001775137056=1')

     3.


                  E 2011-06-18 03:09:36.066

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 03:09:36.070

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

12.
     1.


                  2011-06-18 03:09:05.926 /fetch.py 500 30026ms 54cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9B13E34F6.BEEEEBF6&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:09:05 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30026 cpu_ms=54 api_cpu_ms=0 cpm_usd=0.002044 exit_code=104

     2.


                  E 2011-06-18 03:09:05.560
                  DeadlineExceededError(deadline=30,
                  url='http://0.50.channel.facebook.com/x/3006036453/1355509675/false/p_100001775137056=1')


     3.


                  E 2011-06-18 03:09:05.916 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

13.
     1.


                  2011-06-18 03:09:05.926 /fetch.py 500 30026ms 54cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9B13E34F6.BEEEEBF6&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:09:05 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30026 cpu_ms=54 api_cpu_ms=0 cpm_usd=0.002044 exit_code=104

     2.


                  E 2011-06-18 03:09:05.560

        DeadlineExceededError(deadline=30, url='http://0.50.channel.facebook.com/x/3006036453/1355509675/false/p_100001775137056=1')

     3.


                  E 2011-06-18 03:09:05.916

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 03:09:05.918

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

14.
     1.


                  2011-06-18 03:08:35.635 /fetch.py 500 30012ms 55cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9AF6FFF56.22314BAA&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:08:35 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30012 cpu_ms=55 api_cpu_ms=0 cpm_usd=0.002067 exit_code=104

     2.


                  E 2011-06-18 03:08:35.265
                  DeadlineExceededError(deadline=30,
                  url='http://0.50.channel.facebook.com/x/3006036453/1355509675/false/p_100001775137056=1')


     3.


                  E 2011-06-18 03:08:35.624 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

15.
     1.


                  2011-06-18 03:08:35.635 /fetch.py 500 30012ms 55cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9AF6FFF56.22314BAA&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:08:35 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30012 cpu_ms=55 api_cpu_ms=0 cpm_usd=0.002067 exit_code=104

     2.


                  E 2011-06-18 03:08:35.265

        DeadlineExceededError(deadline=30, url='http://0.50.channel.facebook.com/x/3006036453/1355509675/false/p_100001775137056=1')

     3.


                  E 2011-06-18 03:08:35.624

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 03:08:35.627

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

16.
     1.


                  2011-06-18 03:08:17.135 /fetch.py 500 29862ms 36cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9AE55B6A6.DEF6D21C&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:08:17 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=29863 cpu_ms=37 api_cpu_ms=0 cpm_usd=0.001558 exit_code=104

     2.


                  E 2011-06-18 03:08:16.928
                  DeadlineExceededError(deadline=30,
                  url='http://0.50.channel.facebook.com/x/3723905448/1250588742/false/p_100001775137056=1')


     3.


                  E 2011-06-18 03:08:17.125 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

17.
     1.


                  2011-06-18 03:08:17.135 /fetch.py 500 29862ms 36cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9AE55B6A6.DEF6D21C&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:08:17 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=29863 cpu_ms=37 api_cpu_ms=0 cpm_usd=0.001558 exit_code=104

     2.


                  E 2011-06-18 03:08:16.928

        DeadlineExceededError(deadline=30, url='http://0.50.channel.facebook.com/x/3723905448/1250588742/false/p_100001775137056=1')

     3.


                  E 2011-06-18 03:08:17.125

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 03:08:17.128

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

18.
     1.


                  2011-06-18 03:08:05.355 /fetch.py 500 30070ms 36cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9ADA1F621.473ADF37&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:08:05 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30071 cpu_ms=37 api_cpu_ms=0 cpm_usd=0.001558 exit_code=104

     2.


                  E 2011-06-18 03:08:04.947
                  DeadlineExceededError(deadline=30,
                  url='http://0.50.channel.facebook.com/x/3006036453/1355509675/false/p_100001775137056=1')


     3.


                  E 2011-06-18 03:08:05.344 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

19.
     1.


                  2011-06-18 03:08:05.355 /fetch.py 500 30070ms 36cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9ADA1F621.473ADF37&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:08:05 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30071 cpu_ms=37 api_cpu_ms=0 cpm_usd=0.001558 exit_code=104

     2.


                  E 2011-06-18 03:08:04.947

        DeadlineExceededError(deadline=30, url='http://0.50.channel.facebook.com/x/3006036453/1355509675/false/p_100001775137056=1')

     3.


                  E 2011-06-18 03:08:05.344

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 03:08:05.347

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

20.
     1.


                  2011-06-18 03:06:37.232 /fetch.py 500 30105ms 73cpu_ms
                  0kb gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9A8615203.66099303&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:06:37 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30105 cpu_ms=73 api_cpu_ms=0 cpm_usd=0.002569 exit_code=104

     2.


                  E 2011-06-18 03:06:36.783
                  DeadlineExceededError(deadline=30,
                  url='http://0.50.channel.facebook.com/x/4175601945/2509795788/true/p_100001775137056=0')


     3.


                  E 2011-06-18 03:06:37.181 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

21.
     1.


                  2011-06-18 03:06:37.232 /fetch.py 500 30105ms 73cpu_ms
                  0kb gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9A8615203.66099303&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:06:37 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30105 cpu_ms=73 api_cpu_ms=0 cpm_usd=0.002569 exit_code=104

     2.


                  E 2011-06-18 03:06:36.783

        DeadlineExceededError(deadline=30, url='http://0.50.channel.facebook.com/x/4175601945/2509795788/true/p_100001775137056=0')

     3.


                  E 2011-06-18 03:06:37.181

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 03:06:37.224

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

22.
     1.


                  2011-06-18 03:06:06.862 /fetch.py 500 30106ms 36cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9A691E795.DAC35677&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:06:06 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30106 cpu_ms=37 api_cpu_ms=0 cpm_usd=0.001551 exit_code=104

     2.


                  E 2011-06-18 03:06:06.392
                  DeadlineExceededError(deadline=30,
                  url='http://0.50.channel.facebook.com/x/4175601945/2509795788/true/p_100001775137056=0')


     3.


                  E 2011-06-18 03:06:06.793 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

23.
     1.


                  2011-06-18 03:06:06.862 /fetch.py 500 30106ms 36cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9A691E795.DAC35677&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:06:06 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30106 cpu_ms=37 api_cpu_ms=0 cpm_usd=0.001551 exit_code=104

     2.


                  E 2011-06-18 03:06:06.392

        DeadlineExceededError(deadline=30, url='http://0.50.channel.facebook.com/x/4175601945/2509795788/true/p_100001775137056=0')

     3.


                  E 2011-06-18 03:06:06.793

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 03:06:06.855

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

24.
     1.


                  2011-06-18 03:05:36.487 /fetch.py 500 30646ms 55cpu_ms
                  0kb gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9A4C26C2E.CCF234E8&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:05:36 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30647 cpu_ms=55 api_cpu_ms=0 cpm_usd=0.002060 exit_code=104

     2.


                  E 2011-06-18 03:05:35.677
                  DeadlineExceededError(deadline=30,
                  url='http://0.50.channel.facebook.com/x/4175601945/2509795788/true/p_100001775137056=0')


     3.


                  E 2011-06-18 03:05:36.478 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

25.
     1.


                  2011-06-18 03:05:36.487 /fetch.py 500 30646ms 55cpu_ms
                  0kb gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F9A4C26C2E.CCF234E8&layout=plain>


        203.100.206.5 - - [18/Jun/2011:03:05:36 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=30647 cpu_ms=55 api_cpu_ms=0 cpm_usd=0.002060 exit_code=104

     2.


                  E 2011-06-18 03:05:35.677

        DeadlineExceededError(deadline=30, url='http://0.50.channel.facebook.com/x/4175601945/2509795788/true/p_100001775137056=0')

     3.


                  E 2011-06-18 03:05:36.478

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 03:05:36.481

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

26.
     1.


                  2011-06-18 00:18:49.443 /fetch.py 500 40108ms 18cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F7504B0B22.A58423BC&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:18:49 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=40109 cpu_ms=18 api_cpu_ms=0 cpm_usd=0.000703 exit_code=104

     2.


                  E 2011-06-18 00:18:49.176
                  DeadlineExceededError(deadline=30,
                  url='http://222.186.24.24:9096/attachments/day_101124/1011241650be1e35bf28b5ade2.jpg')


     3.


                  E 2011-06-18 00:18:49.426 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

27.
     1.


                  2011-06-18 00:18:49.443 /fetch.py 500 40108ms 18cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F7504B0B22.A58423BC&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:18:49 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=40109 cpu_ms=18 api_cpu_ms=0 cpm_usd=0.000703 exit_code=104

     2.


                  E 2011-06-18 00:18:49.176

        DeadlineExceededError(deadline=30, url='http://222.186.24.24:9096/attachments/day_101124/1011241650be1e35bf28b5ade2.jpg')

     3.


                  E 2011-06-18 00:18:49.426

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 00:18:49.430

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

28.
     1.


                  2011-06-18 00:18:49.435 /fetch.py 500 40061ms 36cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F7504AEEA5.EA989578&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:18:49 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=40062 cpu_ms=37 api_cpu_ms=0 cpm_usd=0.001212 exit_code=104

     2.


                  E 2011-06-18 00:18:49.175
                  DeadlineExceededError(deadline=30,
                  url='http://222.186.24.24:9096/attachments/day_101124/10112416537793aa71ee836ca7.jpg')


     3.


                  E 2011-06-18 00:18:49.426 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

29.
     1.


                  2011-06-18 00:18:49.435 /fetch.py 500 40061ms 36cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F7504AEEA5.EA989578&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:18:49 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=40062 cpu_ms=37 api_cpu_ms=0 cpm_usd=0.001212 exit_code=104

     2.


                  E 2011-06-18 00:18:49.175

        DeadlineExceededError(deadline=30, url='http://222.186.24.24:9096/attachments/day_101124/10112416537793aa71ee836ca7.jpg')

     3.


                  E 2011-06-18 00:18:49.426

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 00:18:49.429

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

30.
     1.


                  2011-06-18 00:18:48.863 /fetch.py 500 40564ms 55cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F750423320.1ACF8DEA&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:18:48 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=40564 cpu_ms=55 api_cpu_ms=0 cpm_usd=0.001721 exit_code=104

     2.


                  E 2011-06-18 00:18:48.312
                  DeadlineExceededError(deadline=30,
                  url='http://222.186.24.24:9096/attachments/day_101124/101124165058758312c8040157.jpg')


     3.


                  E 2011-06-18 00:18:48.809 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

31.
     1.


                  2011-06-18 00:18:48.863 /fetch.py 500 40564ms 55cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F750423320.1ACF8DEA&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:18:48 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=40564 cpu_ms=55 api_cpu_ms=0 cpm_usd=0.001721 exit_code=104

     2.


                  E 2011-06-18 00:18:48.312

        DeadlineExceededError(deadline=30, url='http://222.186.24.24:9096/attachments/day_101124/101124165058758312c8040157.jpg')

     3.


                  E 2011-06-18 00:18:48.809

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 00:18:48.856

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

32.
     1.


                  2011-06-18 00:18:25.876 /fetch.py 500 34383ms 55cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F74EE373F0.049F2970&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:18:25 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=34383 cpu_ms=55 api_cpu_ms=0 cpm_usd=0.001721 pending_ms=4501 exit_code=104

     2.


                  E 2011-06-18 00:18:25.482
                  DeadlineExceededError(deadline=30,
                  url='http://222.186.24.24:9096/attachments/day_101124/1011241649e46444c20dbff28d.jpg')


     3.


                  E 2011-06-18 00:18:25.867 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

33.
     1.


                  2011-06-18 00:18:25.876 /fetch.py 500 34383ms 55cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F74EE373F0.049F2970&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:18:25 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=34383 cpu_ms=55 api_cpu_ms=0 cpm_usd=0.001721 pending_ms=4501 exit_code=104

     2.


                  E 2011-06-18 00:18:25.482

        DeadlineExceededError(deadline=30, url='http://222.186.24.24:9096/attachments/day_101124/1011241649e46444c20dbff28d.jpg')

     3.


                  E 2011-06-18 00:18:25.867

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

     4.


                  W 2011-06-18 00:18:25.870

        A serious problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. If you see this message frequently, you may be throwing exceptions during the initialization of your application. (Error code 104)

34.
     1.


                  2011-06-18 00:18:09.096 /fetch.py 500 50232ms 36cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F74DE3654E.968D911C&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:18:09 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=50233 cpu_ms=37 api_cpu_ms=0 cpm_usd=0.001212 exit_code=104

     2.


                  E 2011-06-18 00:18:08.882
                  DeadlineExceededError(deadline=30,
                  url='http://222.186.24.24:9096/attachments/day_101124/10112416537793aa71ee836ca7.jpg')


     3.


                  E 2011-06-18 00:18:09.087 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

35.
     1.


                  2011-06-18 00:18:09.096 /fetch.py 500 50232ms 36cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F74DE3654E.968D911C&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:18:09 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=50233 cpu_ms=37 api_cpu_ms=0 cpm_usd=0.001212 exit_code=104

     2.


                  E 2011-06-18 00:18:08.882

        DeadlineExceededError(deadline=30, url='http://222.186.24.24:9096/attachments/day_101124/10112416537793aa71ee836ca7.jpg')

     3.


                  E 2011-06-18 00:18:09.087

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

36.
     1.


                  2011-06-18 00:17:47.499 /fetch.py 500 29960ms 36cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F74C99DD0D.181A1929&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:17:47 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=29960 cpu_ms=37 api_cpu_ms=0 cpm_usd=0.001212 exit_code=104

     2.


                  E 2011-06-18 00:17:47.283
                  DeadlineExceededError(deadline=30,
                  url='http://222.186.24.24:9096/attachments/day_101124/1011241649dedc8a11ee1f824a.jpg')


     3.


                  E 2011-06-18 00:17:47.490 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

37.
     1.


                  2011-06-18 00:17:47.499 /fetch.py 500 29960ms 36cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F74C99DD0D.181A1929&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:17:47 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=29960 cpu_ms=37 api_cpu_ms=0 cpm_usd=0.001212 exit_code=104

     2.


                  E 2011-06-18 00:17:47.283

        DeadlineExceededError(deadline=30, url='http://222.186.24.24:9096/attachments/day_101124/1011241649dedc8a11ee1f824a.jpg')

     3.


                  E 2011-06-18 00:17:47.490

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

38.
     1.


                  2011-06-18 00:17:27.201 /fetch.py 500 40153ms 55cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F74B642290.0681BDF9&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:17:27 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=40154 cpu_ms=55 api_cpu_ms=0 cpm_usd=0.001721 exit_code=104

     2.


                  E 2011-06-18 00:17:26.779
                  DeadlineExceededError(deadline=30,
                  url='http://222.186.24.24:9096/attachments/day_101124/1011241650be1e35bf28b5ade2.jpg')


     3.


                  E 2011-06-18 00:17:27.189 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

39.
     1.


                  2011-06-18 00:17:27.201 /fetch.py 500 40153ms 55cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F74B642290.0681BDF9&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:17:27 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=40154 cpu_ms=55 api_cpu_ms=0 cpm_usd=0.001721 exit_code=104

     2.


                  E 2011-06-18 00:17:26.779

        DeadlineExceededError(deadline=30, url='http://222.186.24.24:9096/attachments/day_101124/1011241650be1e35bf28b5ade2.jpg')

     3.


                  E 2011-06-18 00:17:27.189

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

40.
     1.


                  2011-06-18 00:17:27.199 /fetch.py 500 40127ms 91cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F74B641CCF.C7DA6EE3&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:17:27 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=40128 cpu_ms=92 api_cpu_ms=0 cpm_usd=0.002739 exit_code=104

     2.


                  E 2011-06-18 00:17:26.907
                  DeadlineExceededError(deadline=30,
                  url='http://222.186.24.24:9096/attachments/day_101124/10112416496650d2639629d060.jpg')


     3.


                  E 2011-06-18 00:17:27.189 <class
                  'google.appengine.runtime.DeadlineExceededError'>:
                  Traceback (most recent call last): File
                  "/base/data/home/apps/s~我的gae名字/1.35117452609590

41.
     1.


                  2011-06-18 00:17:27.199 /fetch.py 500 40127ms 91cpu_ms
                  0kb gzip(gfe),gzip(gfe),gzip(gfe)

        See details
        </logs/log_detail?app_id=s~我的gae名字&version_id=1.351254833983301283&request_id=0004A5F74B641CCF.C7DA6EE3&layout=plain>


        221.221.132.238 - - [18/Jun/2011:00:17:27 -0700] "POST /fetch.py HTTP/1.1" 500 0 - "gzip(gfe),gzip(gfe),gzip(gfe)" "我的gae名字.appspot.com" ms=40128 cpu_ms=92 api_cpu_ms=0 cpm_usd=0.002739 exit_code=104

     2.


                  E 2011-06-18 00:17:26.907

        DeadlineExceededError(deadline=30, url='http://222.186.24.24:9096/attachments/day_101124/10112416496650d2639629d060.jpg')

     3.


                  E 2011-06-18 00:17:27.189

        <class 'google.appengine.runtime.DeadlineExceededError'>: 
        Traceback (most recent call last):
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 217, in main
            run_wsgi_app(application)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 98, in run_wsgi_app
            run_bare_wsgi_app(add_wsgi_middleware(application))
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 116, in run_bare_wsgi_app
            result = application(env, _start_response)
          File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
            handler.post(*groups)
          File "/base/data/home/apps/s~我的gae名字/1.351174526095903150/fetch.py", line 137, in post
            time.sleep(1)

42.
    ‹ Prev 20 *1-20 * Next 20 ›
    </logs?app_id=s~我的gae名字&version_id=1.351254833983301283&offset=0004A5F74B641CCF.C7DA6EE3&start_index=21>
    (Bottom: 2 days, 1:53:42 ago)

*Legend:*

  * D Debug (least severe)
  * I Info
  * W Warning
  * E Error
  * C Critical (most severe)

Learn more about logging in your application
<http://code.google.com/appengine/articles/logging.html>.
© 2008 Google | Terms of Service
<http://code.google.com/appengine/terms.html> | Privacy Policy
<http://code.google.com/appengine/privacy.html> | Blog
<http://googleappengine.blogspot.com> | Discussion Forums
<http://groups.google.com/group/google-appengine>
Loading ...
